### ISSUE TITLE
Limpia el repositorio

### ISSUE THREAD

**Issue by pposca** [francessergi/DAW2-M9#1]
Quita todo lo que no sea de clase del repositorio. Deja solo la carpeta UF1 con una carpeta por proyecto.

**Comment by pposca** [comment]
Borra también los archivos .DS_Store, y añádelos al .gitignore para que no se vuelvan a subir.

**Comment by francessergi** [comment]
Hola Pepe, he eliminado los .DS_Store y los he añadido al .gitignore.
He eliminado el curriculum, porque no era de clase.
He dejado el indice con la portada, aunque no esta en las tareas, un dia comentaste que lo hiciéramos en clase.
